### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by AtefehSamadi** [colinator/timit_utils#1]
Hi,
Running the code 
```
corpus = tu.Corpus('../TIMIT')
sentence = corpus.train.sentences_by_phone_df('aa').sentence[0]
du.DrawVerticalPanels([du.AudioPanel(sentence.raw_audio, show_x_axis=True),
                       du.WordsPanel(sentence.words_df, sentence.raw_audio.shape[0], show_x_axis=True),
                       du.PhonesPanel(sentence.phones_df, sentence.raw_audio.shape[0])
                      ])
```

got the error:

```
FileNotFoundError: [WinError 3] The system cannot find the path specified: '../TIMIT\\TRAIN'
```

Could you please help me with this? what should I do?
I have installed timit_utils. 

Thanks in advance
Atefeh

**Comment by colinator** [comment]
Hi Atefeh,

You installed this library (timit_utils), but did you install the actual timit database?

`The actual TIMIT database is NOT included, and is not free. Get it here: https://catalog.ldc.upenn.edu/LDC93S1. This library merely adds convenience, parsing, sampling, drawing, etc.`

**Comment by AtefehSamadi** [comment]
Oh, not really. Thanks for your consideration.
